version: '3'
services:
  #######################################
  # mysql
  #######################################
  mysql:
    image: mysql:5.6
    container_name: sql_container
    hostname: mysql
    network_mode: host
    command: --default-authentication-plugin=mysql_native_password  
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
      MYSQL_DATABASE: 'task_DB'
    volumes:
      - mysql-volume:/var/lib/mysql
  #######################################
  # articles manager
  #######################################
  article_manager:
    container_name: article_manager_container
    hostname: article_manager_service
    network_mode: host
    build:
      context: ../trufla-task
      dockerfile: Dockerfile
    image: article_manager_image
    volumes:
    - ../article-manager/src:/usr/src/service/src
    environment:
     - PORT=${PORT}
     - DB_PORT=${DB_PORT}
     - DB_USERNAME=${DB_USERNAME}
     - DB_PASSWD=${DB_PASSWORD}
     - DB=${DB_DATABASE}
     - DB_HOST=${DB_HOST}
    depends_on:
      - mysql
volumes:
  devshm:
  mysql-volume:
